import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://sso-qa-pub.internal.cleartax.co/v2?product=cleartax&return_path=L2VudGl0eQ==');
  await page.getByPlaceholder('Enter email').click();
  await page.getByPlaceholder('Enter email').click();
  await page.getByPlaceholder('Enter email').fill('clear.testingdashboard+adminrm@gmail.com');
  await page.getByPlaceholder('Password').click();
  await page.getByPlaceholder('Password').fill('dashboardADMINRM1!');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'File a New Return' }).click();
  await page.getByLabel('File a New Return').getByText('Individual').click();
  await page.getByRole('button', { name: 'Skip & Continue' }).click();
  await page.getByLabel('Skip & Proceed').click();
  await page.getByLabel('Continue without Form').click();
  await page.locator('[id="user\\.baseEntity\\.permanentInfo\\.middleName"]').click();
  await page.locator('[id="user\\.baseEntity\\.permanentInfo\\.middleName"]').fill('sdf');
  await page.locator('[id="user\\.baseEntity\\.permanentInfo\\.firstName"]').click();
  await page.locator('[id="user\\.baseEntity\\.permanentInfo\\.firstName"]').fill('sadf');
  await page.locator('[id="user\\.baseEntity\\.permanentInfo\\.lastName"]').click();
  await page.locator('[id="user\\.baseEntity\\.permanentInfo\\.lastName"]').fill('afds');
  await page.getByPlaceholder('DD/MM/YYYY').click();
  await page.getByPlaceholder('DD/MM/YYYY').fill('02/02/1991');
  await page.locator('[id="user\\.baseEntity\\.permanentInfo\\.fatherName"]').click();
  await page.locator('[id="user\\.baseEntity\\.permanentInfo\\.fatherName"]').fill('asdf');
  await page.getByLabel('Female').check();
  await page.locator('#identificationAndContactForm').getByTestId('button').click();
  await page.getByPlaceholder('Enter 10 digit PAN').click();
  await page.getByPlaceholder('Enter 10 digit PAN').fill('EAPPD3322a');
  await page.locator('[id="user\\.baseEntity\\.address\\.mobile"]').click();
  await page.locator('[id="user\\.baseEntity\\.address\\.mobile"]').fill('9876543210');
  await expect(page.getByText('Progess auto-saved')).toBeVisible();
  await page.locator('#addressForm').getByTestId('button').click();
  await page.getByPlaceholder('For ex: 245, 3rd floor').click();
  await page.getByPlaceholder('For ex: 245, 3rd floor').fill('asdf');
  await page.getByPlaceholder('For ex: Jayanagar 5th Block').click();
  await page.getByPlaceholder('For ex: Jayanagar 5th Block').fill('sadf');
  await page.getByPlaceholder('For ex: 560041').click();
  await page.getByPlaceholder('For ex: 560041').fill('282006');
  await page.locator('#bankDetailsCard').getByTestId('button').first().click();
  await page.getByRole('row', { name: 'SAVINGS' }).getByRole('textbox').first().click();
  await page.getByRole('row', { name: 'SAVINGS' }).getByRole('textbox').first().fill('23323232');
  await page.getByRole('row', { name: 'SAVINGS' }).getByRole('textbox').nth(1).click();
  await page.getByRole('row', { name: 'SAVINGS' }).getByRole('textbox').nth(1).fill('sbin000007');
  await page.getByRole('row', { name: 'SAVINGS' }).getByRole('textbox').nth(1).press('ArrowLeft');
  await page.getByRole('cell', { name: 'sbin000007' }).getByRole('textbox').fill('sbin0000007');
  await page.locator('div').filter({ hasText: 'Personal InfoIncome SourcesTax SavingTax SummaryPermanent InformationPlease' }).nth(1).click();
  await page.locator('div').filter({ hasText: 'Personal InfoIncome SourcesTax SavingTax SummaryPermanent InformationPlease' }).nth(1).click();
  await expect(page.getByText('Progess auto-saved')).toBeVisible();
  await page.getByTestId('rhs-container').getByTestId('button').click();
  await page.getByLabel('Add Manually').click();
  await page.getByPlaceholder('Search for Employer Name').click();
  await page.getByPlaceholder('Search for Employer Name').fill('i');
  await page.locator('li').filter({ hasText: 'Tata Consultancy Services Ltd' }).click();
  await page.locator('#tdsSalary').click();
  await page.locator('#tdsSalary').fill('90,0000');
  await page.getByText('Unsaved changes').click();
  await page.locator('div').filter({ hasText: /^1\(a\)\. Salary as per section 17\(1\)\*Sample₹$/ }).getByRole('textbox').click();
  await page.locator('div').filter({ hasText: /^1\(a\)\. Salary as per section 17\(1\)\*Sample₹$/ }).getByRole('textbox').fill('2,50,0000');
  await page.locator('div').filter({ hasText: 'View / Edit SalaryAvoid' }).nth(1).click();
  await expect(page.locator('div').filter({ hasText: /^Progress auto-saved$/ })).toBeVisible();
  await page.getByLabel('Save & Continue').click();
  await page.getByLabel('Tax Summary').click();
  await page.getByLabel('Fix Errors').click();
  await page.getByPlaceholder('eg: email@gmail.com').click();
  await page.getByPlaceholder('eg: email@gmail.com').press('ArrowLeft');
  await page.getByPlaceholder('eg: email@gmail.com').fill('clear.testingdashboardadminrm@gmail.com');
  
  await page.getByText('A few details are missing. Take a minute to complete them!Identification &').click();
  await page.locator('.text-center > svg').click();
  await page.getByTestId('rhs-container').getByTestId('button').click();
  await page.getByRole('button', { name: 'Pay ₹6 & e-file' }).click();
  await page.frameLocator('iframe[title="JuspayFrame"]').getByText('Netbanking').click();
  await page.frameLocator('iframe[title="JuspayFrame"]').getByText('HDFC', { exact: true }).click();
  await page.getByRole('button', { name: 'Success' }).click();
  await page.getByPlaceholder('Enter 12 digit number').click();
  await page.getByPlaceholder('Enter 12 digit number').fill('1212 1212 12121');
  await page.getByTestId('rhs-container').getByTestId('button').click();
  await page.getByRole('button', { name: 'Get OTP' }).click();
  await page.getByLabel('Enter OTP sent toMobileOTP').click();
  await page.getByLabel('Enter OTP sent toMobileOTP').fill('123456');
  await page.getByRole('button', { name: 'Verify OTP' }).click();
  await page.goto('https://cleartax-qa-http.internal.cleartax.co/paytax/y2024/Xm97S7hmVk--jTrEwHJNgw/12/LetsEfile');
  await page.getByRole('button', { name: 'Proceed to e-file' }).click();
  await page.goto('https://cleartax-qa-http.internal.cleartax.co/paytax/y2024/Xm97S7hmVk--jTrEwHJNgw/12/AsyncWaitForJson?identifier=b5687cea-59e4-4536-99ec-4fb263a5d3bb&purpose=SubmitJsonViaEri');
  await page.goto('https://cleartax-qa-http.internal.cleartax.co/paytax/y2024/Xm97S7hmVk--jTrEwHJNgw/12/CheckSubmitStatus?identifier=ba7b51d9-24ca-4652-8a86-f56c440dfdc8&filingId=ba7b51d9-24ca-4652-8a86-f56c440dfdc8');
  await page.goto('https://cleartax-qa-http.internal.cleartax.co/filing/2024/12/Xm97S7hmVk--jTrEwHJNgw/e-filing-success?filingId=ba7b51d9-24ca-4652-8a86-f56c440dfdc8');
  await expect(page.getByText('Congratulations!')).toBeVisible();
  await page.getByRole('button', { name: 'e-Verify Now' }).click();
  await page.getByRole('button', { name: 'Get OTP' }).click();
  await page.getByPlaceholder('Enter the six digit OTP here').click();
  await page.getByPlaceholder('Enter the six digit OTP here').fill('123455');
  await page.getByRole('button', { name: 'Verify OTP' }).click();
  await expect(page.getByText('e-Verification Successful')).toBeVisible();
  await page.getByLabel('Continue').click();
  await page.getByRole('button', { name: '' }).click();
});