import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://sso-dev-pub.internal.cleartax.co/v2?product=cleartax&return_path=L2VudGl0eQ==');
  await page.getByPlaceholder('Enter email').click();
  await page.getByPlaceholder('Enter email').click();
  await page.getByPlaceholder('Enter email').fill('clear.testingdashboard+rm@gmail.com');
  await page.getByPlaceholder('Password').click();
  await page.getByPlaceholder('Password').click();
  await page.getByPlaceholder('Password').fill('dashboardRM1!');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'File a New Return' }).click();
  await page.getByLabel('File a New Return').getByText('Individual').click();
  await page.getByLabel('Skip & Proceed').click();
  await page.getByLabel('Continue without Form').click();
  await page.locator('[id="user\\.baseEntity\\.permanentInfo\\.firstName"]').click();
  await page.locator('[id="user\\.baseEntity\\.permanentInfo\\.firstName"]').fill('sadf');
  await page.locator('[id="user\\.baseEntity\\.permanentInfo\\.lastName"]').click();
  await page.locator('[id="user\\.baseEntity\\.permanentInfo\\.lastName"]').fill('adsf');
  await page.getByPlaceholder('DD/MM/YYYY').click();
  await page.getByPlaceholder('DD/MM/YYYY').fill('12/02/1999');
  await page.locator('[id="user\\.baseEntity\\.permanentInfo\\.fatherName"]').click();
  await page.locator('[id="user\\.baseEntity\\.permanentInfo\\.fatherName"]').fill('asdf');
  await page.getByLabel('Male', { exact: true }).check();
  await page.getByText('To e-file your returns,').click();
  await page.getByPlaceholder('Enter 12 digit number').click();
  await page.getByPlaceholder('Enter 12 digit number').fill('1234 1234 1234');
  await page.getByPlaceholder('Enter 10 digit PAN').click();
  await page.getByPlaceholder('Enter 10 digit PAN').fill('EOFPF9392a');
  await page.locator('[id="user\\.baseEntity\\.address\\.mobile"]').click();
  await page.locator('[id="user\\.baseEntity\\.address\\.mobile"]').fill('9876543210');
  await page.locator('#addressForm').getByTestId('button').click();
  await page.getByPlaceholder('For ex: 245, 3rd floor').click();
  await page.getByPlaceholder('For ex: 245, 3rd floor').fill('afsd');
  await page.locator('div').filter({ hasText: /^Area Locality \*$/ }).first().click();
  await page.getByPlaceholder('For ex: Jayanagar 5th Block').click();
  await page.getByPlaceholder('For ex: Jayanagar 5th Block').fill('sadf');
  await page.getByPlaceholder('For ex: 560041').click();
  await page.getByPlaceholder('For ex: 560041').fill('adfs');
  await page.getByPlaceholder('For ex: Bangalore').click();
  await page.getByPlaceholder('For ex: Bangalore').fill('bangalore');
  await page.locator('#residentialStatusCard').getByTestId('button').first().click();
  await page.locator('#bankDetailsCard').getByTestId('button').first().click();
  await page.getByRole('row', { name: 'SAVINGS' }).getByRole('textbox').first().click();
  await page.getByRole('row', { name: 'SAVINGS' }).getByRole('textbox').first().fill('32232233');
  await page.getByRole('row', { name: 'SAVINGS' }).getByRole('textbox').nth(1).fill('s');
  await page.getByRole('row', { name: 'SAVINGS' }).getByRole('textbox').nth(1).click();
  await page.getByRole('cell', { name: 's', exact: true }).getByRole('textbox').fill('sbin00000007');
  await page.locator('.text-s-16 > .text-center').click();
  await page.getByTestId('rhs-container').getByTestId('button').click();
  await page.locator('.text-s-16 > .text-center').click();
  await page.getByLabel('Add Manually').click();
  await page.getByPlaceholder('Search for Employer Name').click();
  await page.getByPlaceholder('Search for Employer Name').fill('f');
  await page.locator('li').filter({ hasText: 'Tata Consultancy Services Ltd' }).click();
  await page.locator('#tdsSalary').click();
  await page.locator('#tdsSalary').fill('90,0000');

  await page.locator('div').filter({ hasText: /^1\(a\)\. Salary as per section 17\(1\)\*Sample₹$/ }).getByRole('textbox').click();
  
  await page.locator('div').filter({ hasText: /^1\(a\)\. Salary as per section 17\(1\)\*Sample₹$/ }).getByRole('textbox').fill('2,50,0000');
  await page.locator('.text-s-16 > .text-center').click();
  await page.getByLabel('Save & Continue').click();
  await page.getByLabel('Tax Summary').click();
  await page.locator('.text-center > svg').click();
  await page.getByLabel('Fix Errors').click();
  await page.getByPlaceholder('eg: email@gmail.com').click();
  await page.getByPlaceholder('eg: email@gmail.com').click();
  await page.getByPlaceholder('eg: email@gmail.com').press('ArrowRight');
  await page.getByPlaceholder('eg: email@gmail.com').fill('clear.testingdashboard@gmail.com');
  await page.getByPlaceholder('For ex: 560041').click();
  await page.getByPlaceholder('For ex: 560041').fill('282006');
  await page.locator('#addressForm div').filter({ hasText: 'Your AddressYou can provide' }).first().click();
  await page.locator('.text-center > svg > path:nth-child(2)').click();
  await page.getByTestId('rhs-container').getByTestId('button').click();
});