import { app, BrowserWindow, ipcMain } from 'electron';
import TestServies from './testService';
import { registerAllIpcHandlers } from './ipcHandlers';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

let mainWindow: BrowserWindow;

const createWindow = async () => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // Load the index.html of the app.
  await mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
  
  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

export function initializeApp() {
  // This method will be called when Electron has finished
  // initialization and is ready to create browser windows.
  // Some APIs can only be used after this event occurs.
  app.on('ready', () => {
    createWindow();
    
    // Register all IPC handlers
    registerAllIpcHandlers(mainWindow);
    
    // Start periodic cleanup of expired trash items (runs every 24 hours)
    const cleanupInterval = setInterval(async () => {
      try {
        const result = await TestServies.cleanupExpiredTrashItems();
        console.log('Automatic trash cleanup completed:', result);
      } catch (error) {
        console.error('Error during automatic trash cleanup:', error);
      }
    }, 24 * 60 * 60 * 1000); // 24 hours in milliseconds

    // Clean up interval when app is quitting
    app.on('before-quit', () => {
      clearInterval(cleanupInterval);
    });
  });

  // Quit when all windows are closed, except on macOS. There, it's common
  // for applications and their menu bar to stay active until the user quits
  // explicitly with Cmd + Q.
  app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') {
      app.quit();
    }
  });

  app.on('activate', () => {
    // On OS X it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) {
      createWindow();
    }
  });

  // Generic asynchronous handler
  ipcMain.on('anything-asynchronous', (event, arg) => {
    //execute tasks on behalf of renderer process
    // console.log(arg) // prints "ping"
  });
}

export function getMainWindow(): BrowserWindow {
  return mainWindow;
}