import { app, BrowserWindow, ipcMain, ipcRenderer } from 'electron';
import TestServies from './backend/testService';
import { ObjectId } from 'mongodb';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

let mainWindow: BrowserWindow;

const createWindow = async () => {
  // Create the browser window.

  mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });
  // and load the index.html of the app.

  // console.log(">>>>>>TEST>CASES>>>",testCases)
  await mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
  // mainWindow.webContents.send('getAllTestCases', testCases);
  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
  createWindow();
  
  // Start periodic cleanup of expired trash items (runs every 24 hours)
  const cleanupInterval = setInterval(async () => {
    try {
      const result = await TestServies.cleanupExpiredTrashItems();
      console.log('Automatic trash cleanup completed:', result);
    } catch (error) {
      console.error('Error during automatic trash cleanup:', error);
    }
  }, 24 * 60 * 60 * 1000); // 24 hours in milliseconds

  // Clean up interval when app is quitting
  app.on('before-quit', () => {
    clearInterval(cleanupInterval);
  });
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});
ipcMain.handle(
  'recordTest',
  async (
    event: any,
    {
      testCase,
      name,
      preTestId,
      mode,
    }: { testCase: string; name: string; preTestId: string; mode: string }
  ) => {
    // mainWindow.webContents.send('test123',"sdfsfd");

    const testCases = await TestServies.recordTestCase({
      mainWindow,
      testCase,
      name,
      preTestId,
      mode,
    });
    return 'abhishek';
  }
);

ipcMain.handle('recordTestOnLocal', async (event: any, arg: any) => {
  // mainWindow.webContents.send('test123',"sdfsfd");

  const testCases = await TestServies.recordTestCaseOnLocal({
    mainWindow,
    preTestId: arg.preTestId,
    mode: arg.mode,
  });
  return 'abhishek';
});
ipcMain.handle('getAllTestCases', async (event: any, arg: any) => {
  const testCases = await TestServies.getAllTestCases();

  return testCases;
});
ipcMain.handle('run-test', async (event: any, arg: any) => {
  console.log('test case', arg);
  const successfullRun = await TestServies.runTestCase({
    testCase: arg,
    mainWindow,
  });

  return successfullRun;
});

ipcMain.handle('deleteTestCase', async (event: any, arg: any) => {
  try {
    console.log('Deleting test case with ID:', arg.testId);
    const result = await TestServies.deleteTestCase(arg.testId);
    return result;
  } catch (error) {
    console.error('Error in deleteTestCase IPC handler:', error);
    return { success: false, message: 'IPC handler error: ' + error.message };
  }
});

ipcMain.handle('updateTestCase', async (event: any, arg: any) => {
  try {
    if (!arg) {
      console.error('No arguments provided in IPC call');
      return { success: false, message: 'No arguments provided' };
    }
    
    if (!arg.testId) {
      console.error('No testId provided in IPC call');
      return { success: false, message: 'Test ID is required' };
    }
    
    if (!arg.updatedData) {
      console.error('No updatedData provided in IPC call');
      return { success: false, message: 'Updated data is required' };
    }
    
    const result = await TestServies.updateTestCase(arg.testId, arg.updatedData);
    console.log('Backend method completed with result:', result);
    
    if (!result) {
      console.error('Backend returned null/undefined result');
      return { success: false, message: 'Backend returned no result' };
    }
    
    return result;
    
  } catch (error) {
    console.error('Full error object:', error);
    
    const errorResult = {
      success: false,
      message: `IPC handler error: ${error?.message || error?.toString() || 'Unknown IPC error'}`
    };
    return errorResult;
  }
});

// Trash functionality IPC handlers
ipcMain.handle('getAllTrashItems', async (event: any, arg: any) => {
  try {
    const trashItems = await TestServies.getAllTrashItems();
    return trashItems;
  } catch (error) {
    console.error('Error in getAllTrashItems IPC handler:', error);
    return [];
  }
});

ipcMain.handle('restoreTestCase', async (event: any, arg: any) => {
  try {
    console.log('Restoring test case with ID:', arg.trashId);
    const result = await TestServies.restoreTestCase(arg.trashId);
    return result;
  } catch (error) {
    console.error('Error in restoreTestCase IPC handler:', error);
    return { success: false, message: 'IPC handler error: ' + error.message };
  }
});

ipcMain.handle('permanentDeleteTestCase', async (event: any, arg: any) => {
  try {
    console.log('Permanently deleting test case with ID:', arg.trashId);
    const result = await TestServies.permanentDeleteTestCase(arg.trashId);
    return result;
  } catch (error) {
    console.error('Error in permanentDeleteTestCase IPC handler:', error);
    return { success: false, message: 'IPC handler error: ' + error.message };
  }
});

ipcMain.handle('cleanupExpiredTrashItems', async (event: any, arg: any) => {
  try {
    const result = await TestServies.cleanupExpiredTrashItems();
    return result;
  } catch (error) {
    console.error('Error in cleanupExpiredTrashItems IPC handler:', error);
    return { success: false, message: 'IPC handler error: ' + error.message };
  }
});

ipcMain.handle('deleteAllTrashItems', async (event: any, arg: any) => {
  try {
    console.log('Deleting all trash items via IPC...');
    const result = await TestServies.deleteAllTrashItems();
    return result;
  } catch (error) {
    console.error('Error in deleteAllTrashItems IPC handler:', error);
    return { success: false, message: 'IPC handler error: ' + error.message };
  }
});

ipcMain.on('anything-asynchronous', (event, arg) => {
  //execute tasks on behalf of renderer process
  // console.log(arg) // prints "ping"
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
// ipcRenderer.send('anything-asynchronous', 'ping')
